# Generated by Django 5.1.5 on 2025-01-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_user'),
        ('user', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='users', to='task.task'),
        ),
    ]
