# Generated by Django 5.1.6 on 2025-04-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_badge_icon_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badge_icons/'),
        ),
    ]
