# Generated by Django 5.1.6 on 2025-04-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pomodoro_count',
            field=models.IntegerField(default=0),
        ),
    ]
