# Generated by Django 5.1.6 on 2025-04-20 07:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_pomodoro_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('pomodoro', 'Pomodoro'), ('tasks', 'Tasks'), ('early_bird', 'Early Bird'), ('focus', 'Focus Time')], max_length=20)),
                ('target', models.IntegerField()),
                ('xp_reward', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.challengetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('daily_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dailychallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
