# Generated by Django 5.1.6 on 2025-04-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_challengetemplate_dailychallenge_userchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengetemplate',
            name='challenge_type',
            field=models.CharField(choices=[('pomodoro', 'Pomodoro'), ('tasks', 'Tasks')], max_length=20),
        ),
    ]
