# Generated by Django 5.1.6 on 2025-03-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_customuser_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
