# Generated by Django 5.1.6 on 2025-06-10 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='completed',
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
