# Generated by Django 5.1.6 on 2025-07-06 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_customuser_onboarding_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_analytics', to=settings.AUTH_USER_MODEL),
        ),
    ]
