# Generated by Django 5.1.6 on 2025-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_usertaskanalytics_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
