# Generated by Django 5.1.6 on 2025-04-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskcompletiondetails_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-last_visited_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='last_visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
