# Generated by Django 5.1.5 on 2025-01-28 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompletionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_details', models.TextField()),
                ('completion_files', models.JSONField(default=list)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='completion_files/')),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='completion_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_details', to='task.task')),
            ],
        ),
    ]
