# Generated by Django 5.1.6 on 2025-04-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_options_task_last_visited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
