# Generated by Django 5.1.5 on 2025-01-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskcompletiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletiondetails',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_details', to='task.task'),
        ),
    ]
