# Generated by Django 5.1.6 on 2025-04-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_is_active_task_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-is_active', '-is_pinned', '-created_at']},
        ),
    ]
