# Generated by Django 5.1.5 on 2025-01-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_taskcompletiondetails_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='shareable',
            field=models.BooleanField(default=True),
        ),
    ]
