# Generated by Django 5.1.5 on 2025-02-01 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_task_helper_helperfeedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompletiondetails',
            name='helper_feedback',
        ),
        migrations.RemoveField(
            model_name='task',
            name='helper',
        ),
        migrations.AddField(
            model_name='task',
            name='task_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnered_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PartnerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_feedbacks', to='task.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskcompletiondetails',
            name='partner_feedback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_details', to='task.partnerfeedback'),
        ),
        migrations.DeleteModel(
            name='HelperFeedback',
        ),
    ]
