# Generated by Django 5.1.5 on 2025-02-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_tasknotes_taskdependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(related_name='dependent_tasks', through='task.TaskDependency', to='task.task'),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='dependent_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_task_dependencies', to='task.task'),
        ),
        migrations.AlterField(
            model_name='taskdependency',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_dependencies', to='task.task'),
        ),
    ]
