# Generated by Django 5.1.5 on 2025-02-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_task_dependencies_alter_taskdependency_dependent_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='procedure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
