# Generated by Django 5.1.5 on 2025-02-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_task_procedure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskNotes',
        ),
    ]
