# Generated by Django 5.1.6 on 2025-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_teaminvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
