# Generated by Django 5.1.6 on 2025-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_alter_teaminvitation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
    ]
