# Generated by Django 5.1.6 on 2025-03-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_task_escalated_to_team_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='escalation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
