# Generated by Django 5.1.6 on 2025-03-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_task_escalation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
