# Generated by Django 5.1.6 on 2025-03-08 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('task', '0031_appreciation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_permissions', to='task.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user', 'permission')},
            },
        ),
    ]
