# Generated by Django 5.1.6 on 2025-03-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0032_teampermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='monthly_goals',
            field=models.JSONField(blank=True, help_text='List of monthly goals', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='vision',
            field=models.TextField(blank=True, help_text='Team vision statement', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='yearly_goals',
            field=models.JSONField(blank=True, help_text='List of yearly goals', null=True),
        ),
    ]
