# Generated by Django 5.1.6 on 2025-03-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0033_team_monthly_goals_team_vision_team_yearly_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='weekly_goals',
            field=models.JSONField(blank=True, help_text='List of weekly goals', null=True),
        ),
    ]
