[jenkins]
jenkins_server ansible_host=your-jenkins-server-ip ansible_user=ec2-user ansible_become=yes

[docker]
docker_hosts ansible_host=your-docker-server-ip ansible_user=ec2-user ansible_become=yes

[kubernetes]
k8s_master ansible_host=your-k8s-master-ip ansible_user=ec2-user ansible_become=yes

[all:vars]
ansible_python_interpreter=/usr/bin/python3
