# Generated by Django 5.1.6 on 2025-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_teamchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchat',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
    ]
