# Generated by Django 5.1.6 on 2025-04-19 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_task_management', '0001_initial'),
        ('task', '0004_alter_task_options_task_last_visited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='microtask',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='microtasks', to='task.subtask'),
        ),
        migrations.AlterField(
            model_name='microtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microtasks', to='task.task'),
        ),
    ]
