# Generated by Django 5.1.6 on 2025-04-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_task_management', '0002_microtask_subtask_alter_microtask_task'),
        ('task', '0004_alter_task_options_task_last_visited_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='microtask',
            unique_together={('subtask', 'title')},
        ),
    ]
